# Generated by Django 4.2.4 on 2023-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='description',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETEd'), ('F', 'PENDING')], default='exit', max_length=2),
            preserve_default=False,
        ),
    ]
