# Generated by Django 4.2.4 on 2023-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_tasklist_complete_remove_tasklist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETEd'), ('P', 'PENDING')], max_length=2),
        ),
    ]
