# Generated by Django 4.2.4 on 2023-11-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tasklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
