# Generated by Django 4.2.7 on 2023-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tasklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='schedule',
            field=models.TimeField(default='exit'),
            preserve_default=False,
        ),
    ]
